name: 10 Controlling execution flow

on: 
    workflow_dispatch:
        inputs:
            pass-unit-tests:
                type: boolean
                description: Whether unit test will pass or not
                default: true

jobs:
    lint-buld:
        runs-on: ubuntu-latest
        steps:
          - name: lint and build
            run: echo "Linting and building the code"
    unit-test:
        runs-on: ubuntu-latest
        steps:
          - name: Running unit tests
            run: echo "Running unit tests"
          - name: failing tests
            if: ${{ !inputs.pass-unit-tests }}
            run: 
    deploy-nonprod:
        runs-on: ubuntu-latest
        needs:
            - lint-buld
            - unit-test
        steps:
          - name: Deploying to non-prod environment
            run: echo "Deploying to non-prod environment"
    e2e-tests:
        runs-on: ubuntu-latest
        needs: deploy-nonprod
        steps:
          - name: Running E2E tests
            run: echo "Running E2E tests"

    load-test:
        runs-on: ubuntu-latest
        needs: deploy-nonprod
        steps:
          - name: Running load tests
            run: echo "Running load tests"   
    deploy-prod:
        runs-on: ubuntu-latest
        needs:
            - e2e-tests
            - load-test
        steps:
          - name: Deploying to prod environment
            run: echo "Deploying to prod environment"

